// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: products.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createdProduct = `-- name: CreatedProduct :one
INSERT INTO products (
    seller_id, product_name, description, baseprice, auction_end
) VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreatedProductParams struct {
	SellerID    uuid.UUID `json:"seller_id"`
	ProductName string    `json:"product_name"`
	Description string    `json:"description"`
	Baseprice   float64   `json:"baseprice"`
	AuctionEnd  time.Time `json:"auction_end"`
}

func (q *Queries) CreatedProduct(ctx context.Context, arg CreatedProductParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createdProduct,
		arg.SellerID,
		arg.ProductName,
		arg.Description,
		arg.Baseprice,
		arg.AuctionEnd,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
